[package]
name = "projeto"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
sqlx = { version = "0.7", features = ["mysql", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "1.0", features = ["full"] }
